Vagrant.configure(2) do |config|
	config.vm.box = "ubuntu"
	config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-i386-vagrant-disk1.box"
	
	config.vm.synced_folder "./../", "/var/www/gantt_project"
	config.vm.provision :shell, :path => "bootstrap.sh"
	config.vm.network :forwarded_port, host: 2000, guest: 3000
end
